project:
  type: website
  output-dir: docs

website:
  title: "Neha's Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



